### ISSUE TITLE
create a .gitignore file and avoid checking binary files into source control

### ISSUE THREAD

**Issue by rsalmond** [MFS-DingDong/DingDong#1]
I noticed we've got a copy of the sqlite database file in source control. It's almost always a bad idea to store binary data in git. Git is very good at storing and managing text data (source code) and pretty bad at everything else. Some background info [here](https://robinwinslow.uk/dont-ever-commit-binary-files-to-git) and [here](https://learn.microsoft.com/en-us/azure/devops/repos/git/manage-large-files?view=azure-devops).

Sometimes it makes sense, but most of the time it's a bad idea, especially if the file changes often, like the contents of a database file. To prevent the database file from showing up in source control we should add a `.gitignore` file to this repo which [can be used](https://docs.github.com/en/get-started/getting-started-with-git/ignoring-files) to prevent certain file extensions or whole directories from being managed by git.

**Comment by wayne868** [comment]
so i did a git rm --cached db.sqlite3
then a git commit and a git push origin to remove the db from the repository, how does it look now?

**Comment by rsalmond** [comment]
@wayne868 nice yeah the file is gone now! Two things to help improve the process:

1. without a .gitignore file there's nothing stopping us from accidentally adding it again, we should still create one.
2. next time you're ready to commit a fix for an open issue like this one, create a branch, commit your work on that branch, and then submit a pull request.

**Comment by wayne868** [comment]
Hey Rob i don't know why but i did a commit and the db.sqlite3 came back. i created a .gitignore and added .sqlite3 to it but it still comes up, what am i doing wrong.

**Comment by rsalmond** [comment]
I can't tell what's wrong until I can see the change ;)

Add your .gitignore to a branch and create a pull request so I can see how it looks.

**Comment by wayne868** [comment]
i think i did it??
